// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolWeb.Data;

#nullable disable

namespace SchoolWeb.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250605202809_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("SchoolWeb.Models.Klasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ausbildungsrichtung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KlassenlehrerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Schulstufe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlassenlehrerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Klassen");
                });

            modelBuilder.Entity("SchoolWeb.Models.Klassenraum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCynap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Plaetze")
                        .HasColumnType("INTEGER");

                    b.Property<float>("RaumInQm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Klassenraeume");
                });

            modelBuilder.Entity("SchoolWeb.Models.Lehrer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BildUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Erfahrung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Fachbereich")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Geburtstag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstKlassenlehrer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Kuerzel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Kuerzel")
                        .IsUnique();

                    b.ToTable("Lehrer");
                });

            modelBuilder.Entity("SchoolWeb.Models.Schueler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Geburtstag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Klasse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KlasseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlasseId");

                    b.HasIndex("Geburtstag", "Klasse")
                        .IsUnique();

                    b.ToTable("Schueler");
                });

            modelBuilder.Entity("SchoolWeb.Models.SchuelerKlassenraum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlassenraumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchuelerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlassenraumId");

                    b.HasIndex("SchuelerId");

                    b.ToTable("SchuelerKlassenraeume");
                });

            modelBuilder.Entity("SchoolWeb.Models.Klasse", b =>
                {
                    b.HasOne("SchoolWeb.Models.Lehrer", "Klassenlehrer")
                        .WithMany("BetreulteKlassen")
                        .HasForeignKey("KlassenlehrerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Klassenlehrer");
                });

            modelBuilder.Entity("SchoolWeb.Models.Schueler", b =>
                {
                    b.HasOne("SchoolWeb.Models.Klasse", null)
                        .WithMany("Schueler")
                        .HasForeignKey("KlasseId");
                });

            modelBuilder.Entity("SchoolWeb.Models.SchuelerKlassenraum", b =>
                {
                    b.HasOne("SchoolWeb.Models.Klassenraum", "Klassenraum")
                        .WithMany("SchuelerKlassenraeume")
                        .HasForeignKey("KlassenraumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWeb.Models.Schueler", "Schueler")
                        .WithMany("SchuelerKlassenraeume")
                        .HasForeignKey("SchuelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klassenraum");

                    b.Navigation("Schueler");
                });

            modelBuilder.Entity("SchoolWeb.Models.Klasse", b =>
                {
                    b.Navigation("Schueler");
                });

            modelBuilder.Entity("SchoolWeb.Models.Klassenraum", b =>
                {
                    b.Navigation("SchuelerKlassenraeume");
                });

            modelBuilder.Entity("SchoolWeb.Models.Lehrer", b =>
                {
                    b.Navigation("BetreulteKlassen");
                });

            modelBuilder.Entity("SchoolWeb.Models.Schueler", b =>
                {
                    b.Navigation("SchuelerKlassenraeume");
                });
#pragma warning restore 612, 618
        }
    }
}
